SportsStore.WebUI/Controllers/NavController.cs
using SportsStore.Domain.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private EFDbContext _dbContext = new EFDbContext();

        // GET: Nav
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Menu(string category = null, bool horizontalLayout = false)
        {
            IEnumerable<string> categories = _dbContext.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            this.ViewBag.category = category;
            string viewName = horizontalLayout ? "MenuHorizontal" : "Menu";
            return PartialView(viewName, categories);
        }
    }
}

SportsStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain;
using SportsStore.Domain.Concrete;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        public const int ITEMS_SIZE_PER_PAGE = 4;

        private EFDbContext _dbContext = new EFDbContext();

        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ViewResult List(string category, int page = 1)
        {
            var vm = new ProductListVM();

            vm.PageIndex = page;
            vm.Category = category;

            vm.Products = _dbContext.Products.
                Where(p => string.IsNullOrEmpty(category) || p.Category == category).
                OrderBy(p => p.ProductID).
                Skip((page - 1) * ITEMS_SIZE_PER_PAGE).
                Take(ITEMS_SIZE_PER_PAGE);

            vm.PageCount = (int)Math.Ceiling((decimal)
                _dbContext.Products.Where(p => string.IsNullOrEmpty(category) || p.Category == category).Count() /
                ITEMS_SIZE_PER_PAGE);

            return View(vm);
        }

        public FileContentResult GetImage(int productId)
        {
            var product = _dbContext.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                return File(product.ImageData, product.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="well">

    @if (this.Model.ImageData != null)
    {
        <div class="pull-left" style="margin-right:10px;">

            <img 
                 class="img-thumbnail" 
                 width="75" 
                 height="75" 
                 src="@Url.Action("GetImage", "Product", new { this.Model.ProductID })"/>

        </div>
    }

    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>

    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(p => p.ProductID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart" />
        </div>
    }

    <span class="lead">@Model.Description</span>
</div>

SportsStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <div>
        @if (this.TempData["message"] != null)
        {
            <div class="alert alert-success">@this.TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />

    <title>@ViewBag.Title</title>

    <style>
        .navbar-right {
            float: right !important;
            margin-left: 15px;
            margin-right: 15px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
            <span class="hidden-xs">SPORTS STORE</span>
            <div class="visible-xs">SPORTS</div>
            <div class="visible-xs">STORE</div>
        </a>

        @Html.Action("Summary", "Cart")
    </div>

    <div class="visible-xs">
        @Html.Action("Menu", "Nav", new { horizontalLayout = true })
    </div>

    <div class="row panel">
        <div id="categories" class="col-sm-3 hidden-xs">
            @Html.Action("Menu", "Nav")
        </div>

        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>