SportsStore.WebUI/Controllers/AdminController.cs
using SportsStore.Domain.Concrete;
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private EFDbContext _dbContext = new EFDbContext();

        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        // GET: Admin
        public ActionResult Index()
        {
            return View(_dbContext.Products);
        }

        public ViewResult Edit(int productId)
        {
            var product = _dbContext.Products.FirstOrDefault(p => p.ProductID == productId);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase image = null)
        {
            if (!this.ModelState.IsValid)
                return View(product);



            if (product.ProductID == 0)
            {
                _dbContext.Products.Add(product);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }



            var productFound = _dbContext.Products.FirstOrDefault(p => p.ProductID == product.ProductID);

            if (productFound == null)
                return RedirectToAction("Index");



            productFound.Name = product.Name;
            productFound.Price = product.Price;
            productFound.Category = product.Category;
            productFound.Description = product.Description;

            if (image == null)
            {
                productFound.ImageMimeType = null;
                productFound.ImageData = null;
            }
            else
            {
                productFound.ImageMimeType = image.ContentType;
                productFound.ImageData = new byte[image.ContentLength];
                image.InputStream.Read(productFound.ImageData, 0, image.ContentLength);
            }

            _dbContext.SaveChanges();
            this.TempData["message"] = string.Format("{0} has been saved.", product.Name);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int productId)
        {
            var product = _dbContext.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                _dbContext.Products.Remove(product);
                _dbContext.SaveChanges();
                this.TempData["message"] = product.Name + " has been deleted.";
            }

            return RedirectToAction("Index");
        }
    }
}

SportsStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain;
using SportsStore.Domain.Concrete;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        public const int ITEMS_SIZE_PER_PAGE = 4;

        private EFDbContext _dbContext = new EFDbContext();

        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ViewResult List(string category, int page = 1)
        {
            var vm = new ProductListVM();

            vm.PageIndex = page;
            vm.Category = category;

            vm.Products = _dbContext.Products.
                Where(p => string.IsNullOrEmpty(category) || p.Category == category).
                OrderBy(p => p.ProductID).
                Skip((page - 1) * ITEMS_SIZE_PER_PAGE).
                Take(ITEMS_SIZE_PER_PAGE);

            vm.PageCount = (int)Math.Ceiling((decimal)
                _dbContext.Products.Where(p => string.IsNullOrEmpty(category) || p.Category == category).Count() /
                ITEMS_SIZE_PER_PAGE);

            return View(vm);
        }

        public FileContentResult GetImage(int productId)
        {
            var product = _dbContext.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                return File(product.ImageData, product.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

SportsStore.WebUI/Views/Admin/Edit.cshtml
@model SportsStore.Domain.Entities.Product

@{
    ViewBag.Title = "Admin: Edit " + this.Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Edit @this.Model.Name</h3>
    </div>
</div>

@using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="panel-body">
        @Html.HiddenFor(m => m.ProductID)
        @foreach (var property in this.ViewData.ModelMetadata.Properties)
        {
            switch (property.PropertyName)
            {
                case "ProductID":
                case "ImageData":
                case "ImageMimeType":
                    break;
                default:
                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Description")
                        {
                            @Html.TextArea(property.PropertyName, null, new { @class = "form-control", row = 5 })
                        }
                        else
                        {
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                        }
                    </div>
                        break;
            }
        }

        <div class="form-group">
            <div style="position:relative;">
                <label>Image</label>
                <a class="btn" href="javascript:;">
                    Choose File...

                    <input type="file"
                           name="Image"
                           size="40"
                           style="position:absolute;z-index:2;top:0;left:0;filter:alpha(opacity=0);opacity:0;background-color:transparent;color:transparent;"
                           onchange='$("#upload-file-info").html($(this).val());' />

                    <span class="label label-info" id="upload-file-info"></span>

                </a>
            </div>

            @if (this.Model.ImageData == null)
            {
                <div class="form-control-static">No Image</div>
            }
            else
            {
                <img 
                     class="img-thumbnail" 
                     width="150" 
                     height="150" 
                     src="@Url.Action("GetImage", "Product", new {this.Model.ProductID})" />
            }

        </div>
    </div>

    <div class="panel-footer">
        <input type="submit" value="Save" class="btn btn-primary" />
        @Html.ActionLink("Cancel and return to List", "Index", null, new { @class = "btn btn-default" })
    </div>
}

SportsStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<SportsStore.Domain.Entities.Product>

@{
    ViewBag.Title = "Admin: All Products";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>All Products</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Name</th>
                <th class="text-right">Price</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach (var item in this.Model)
            {
                <tr>
                    <td class="text-right">@item.ProductID</td>
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductID })</td>
                    <td class="text-right">@item.Price.ToString("c")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("ProductID", item.ProductID)
                            <input type="submit" class="btn btn-default btn-xs" value="Delete" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add a new product", "Create", null, new { @class = "btn btn-default" })
    </div>
</div>